### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by laughing429** [SherlockLiao/Char-RNN-PyTorch#1]
作者您好，我这边运行了您提供的代码。训练模型的时候我使用了17MB的搜狗新闻数据，训练迭代了1000次。可是在生成文本的时候，效果并不是很好。本人也是神经网络初学者，我想请问下对于训练数据，有没有需要注意的地方呢？谢谢！

**Comment by L1aoXingyu** [comment]
我最近更新一下，你可以再试试

**Comment by laughing429** [comment]
好的，我最近也在学习大神的源码。

**Comment by laughing429** [comment]
作者您好，我这边自己训练了一个模型，可是在预测的时候，报了一个在word_to_vec中，权重文件的维度和模型的维度不一致的错。这是什么原因呢？
`RuntimeError: While copying the parameter named word_to_vec.weight, whose dimensions in the model are torch.Size([2504, 512]) and whose dimensions in the checkpoint are torch.Size([2340, 512]).`

**Comment by L1aoXingyu** [comment]
你训练的模型权重和你新定义的模型不一样，定义模型的时候需要传入文本信息来决定词向量的维度

**Comment by laughing429** [comment]
哦哦，我知道了。我在训练的时候又在不断的加入训练数据，搞忘了。谢谢！
